In [5]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp38-cp38-win_amd64.whl.metadata (1.2 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.20.3-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in d:\projects\mlproject1\penv\lib\site-packages (from catboost) (3.7.5)
Requirement already satisfied: numpy<3.0,>=1.16.0 in d:\projects\mlproject1\penv\lib\site-packages (from catboost) (1.24.4)
Requirement already satisfied: pandas<4.0,>=0.24 in d:\projects\mlproject1\penv\lib\site-packages (from catboost) (2.0.3)
Requirement already satisfied: scipy in d:\projects\mlproject1\penv\lib\site-packages (from catboost) (1.10.1)
Collecting plotly (from catboost)
  Downloading plotly-6.6.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: six in d:\projects\mlproject1\penv\lib\site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\projects\mlproject1\penv\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in d:\projects\mlproject1\penv\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\projects\mlproject1\penv\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in d:\projects\mlproject1\penv\lib\site-packages (from matplotlib->catboost) (1.1.1)
Requirement already satisfied: cycler>=0.10 in d:\projects\mlproject1\penv\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\projects\mlproject1\penv\lib\site-packages (from matplotlib->catboost) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\projects\mlproject1\penv\lib\site-packages (from matplotlib->catboost) (1.4.7)
Requirement already satisfied: packaging>=20.0 in d:\projects\mlproject1\penv\lib\site-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=6.2.0 in d:\projects\mlproject1\penv\lib\site-packages (from matplotlib->catboost) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\projects\mlproject1\penv\lib\site-packages (from matplotlib->catboost) (3.1.4)
Requirement already satisfied: importlib-resources>=3.2.0 in d:\projects\mlproject1\penv\lib\site-packages (from matplotlib->catboost) (6.4.5)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-1.42.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: zipp>=3.1.0 in d:\projects\mlproject1\penv\lib\site-packages (from importlib-resources>=3.2.0->matplotlib->catboost) (3.20.2)
Downloading catboost-1.2.10-cp38-cp38-win_amd64.whl (100.3 MB)
   ---------------------------------------- 0.0/100.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.3 MB ? eta -:--:--
   ---------------------------------------- 0.5/100.3 MB 1.3 MB/s eta 0:01:18
   ---------------------------------------- 0.8/100.3 MB 1.2 MB/s eta 0:01:26
   ---------------------------------------- 1.0/100.3 MB 1.3 MB/s eta 0:01:15
    --------------------------------------- 1.3/100.3 MB 1.3 MB/s eta 0:01:17
    --------------------------------------- 1.6/100.3 MB 1.2 MB/s eta 0:01:21
    --------------------------------------- 1.8/100.3 MB 1.3 MB/s eta 0:01:16
    --------------------------------------- 2.1/100.3 MB 1.3 MB/s eta 0:01:16
    --------------------------------------- 2.4/100.3 MB 1.3 MB/s eta 0:01:16
   - -------------------------------------- 2.6/100.3 MB 1.3 MB/s eta 0:01:16
   - -------------------------------------- 2.9/100.3 MB 1.3 MB/s eta 0:01:15
   - -------------------------------------- 3.1/100.3 MB 1.3 MB/s eta 0:01:15
   - -------------------------------------- 3.4/100.3 MB 1.3 MB/s eta 0:01:15
   - -------------------------------------- 3.7/100.3 MB 1.3 MB/s eta 0:01:15
   - -------------------------------------- 3.9/100.3 MB 1.3 MB/s eta 0:01:15
   - -------------------------------------- 4.2/100.3 MB 1.3 MB/s eta 0:01:15
   - -------------------------------------- 4.5/100.3 MB 1.3 MB/s eta 0:01:14
   - -------------------------------------- 4.7/100.3 MB 1.3 MB/s eta 0:01:14
   - -------------------------------------- 5.0/100.3 MB 1.3 MB/s eta 0:01:14
   -- ------------------------------------- 5.2/100.3 MB 1.3 MB/s eta 0:01:14
   -- ------------------------------------- 5.5/100.3 MB 1.3 MB/s eta 0:01:14
   -- ------------------------------------- 5.8/100.3 MB 1.3 MB/s eta 0:01:13
   -- ------------------------------------- 6.0/100.3 MB 1.3 MB/s eta 0:01:13
   -- ------------------------------------- 6.3/100.3 MB 1.3 MB/s eta 0:01:13
   -- ------------------------------------- 6.6/100.3 MB 1.3 MB/s eta 0:01:13
   -- ------------------------------------- 6.8/100.3 MB 1.3 MB/s eta 0:01:13
   -- ------------------------------------- 7.1/100.3 MB 1.3 MB/s eta 0:01:13
   -- ------------------------------------- 7.3/100.3 MB 1.3 MB/s eta 0:01:12
   --- ------------------------------------ 7.6/100.3 MB 1.3 MB/s eta 0:01:12
   --- ------------------------------------ 7.9/100.3 MB 1.3 MB/s eta 0:01:12
   --- ------------------------------------ 8.1/100.3 MB 1.3 MB/s eta 0:01:12
   --- ------------------------------------ 8.4/100.3 MB 1.3 MB/s eta 0:01:11
   --- ------------------------------------ 8.7/100.3 MB 1.3 MB/s eta 0:01:11
   --- ------------------------------------ 8.9/100.3 MB 1.3 MB/s eta 0:01:11
   --- ------------------------------------ 9.2/100.3 MB 1.3 MB/s eta 0:01:11
   --- ------------------------------------ 9.4/100.3 MB 1.3 MB/s eta 0:01:11
   --- ------------------------------------ 9.7/100.3 MB 1.3 MB/s eta 0:01:10
   --- ------------------------------------ 10.0/100.3 MB 1.3 MB/s eta 0:01:10
   ---- ----------------------------------- 10.2/100.3 MB 1.3 MB/s eta 0:01:10
   ---- ----------------------------------- 10.5/100.3 MB 1.3 MB/s eta 0:01:10
   ---- ----------------------------------- 10.7/100.3 MB 1.3 MB/s eta 0:01:10
   ---- ----------------------------------- 11.0/100.3 MB 1.3 MB/s eta 0:01:09
   ---- ----------------------------------- 11.3/100.3 MB 1.3 MB/s eta 0:01:09
   ---- ----------------------------------- 11.5/100.3 MB 1.3 MB/s eta 0:01:09
   ---- ----------------------------------- 11.8/100.3 MB 1.3 MB/s eta 0:01:09
   ---- ----------------------------------- 12.1/100.3 MB 1.3 MB/s eta 0:01:09
   ---- ----------------------------------- 12.3/100.3 MB 1.3 MB/s eta 0:01:08
   ----- ---------------------------------- 12.6/100.3 MB 1.3 MB/s eta 0:01:08
   ----- ---------------------------------- 12.8/100.3 MB 1.3 MB/s eta 0:01:08
   ----- ---------------------------------- 13.1/100.3 MB 1.3 MB/s eta 0:01:08
   ----- ---------------------------------- 13.4/100.3 MB 1.3 MB/s eta 0:01:08
   ----- ---------------------------------- 13.6/100.3 MB 1.3 MB/s eta 0:01:07
   ----- ---------------------------------- 13.9/100.3 MB 1.3 MB/s eta 0:01:07
   ----- ---------------------------------- 14.2/100.3 MB 1.3 MB/s eta 0:01:07
   ----- ---------------------------------- 14.7/100.3 MB 1.3 MB/s eta 0:01:07
   ----- ---------------------------------- 14.9/100.3 MB 1.3 MB/s eta 0:01:06
   ------ --------------------------------- 15.2/100.3 MB 1.3 MB/s eta 0:01:06
   ------ --------------------------------- 15.5/100.3 MB 1.3 MB/s eta 0:01:06
   ------ --------------------------------- 15.7/100.3 MB 1.3 MB/s eta 0:01:06
   ------ --------------------------------- 16.0/100.3 MB 1.3 MB/s eta 0:01:06
   ------ --------------------------------- 16.3/100.3 MB 1.3 MB/s eta 0:01:05
   ------ --------------------------------- 16.5/100.3 MB 1.3 MB/s eta 0:01:05
   ------ --------------------------------- 16.8/100.3 MB 1.3 MB/s eta 0:01:05
   ------ --------------------------------- 17.0/100.3 MB 1.3 MB/s eta 0:01:05
   ------ --------------------------------- 17.3/100.3 MB 1.3 MB/s eta 0:01:05
   ------- -------------------------------- 17.6/100.3 MB 1.3 MB/s eta 0:01:04
   ------- -------------------------------- 17.8/100.3 MB 1.3 MB/s eta 0:01:04
   ------- -------------------------------- 18.1/100.3 MB 1.3 MB/s eta 0:01:04
   ------- -------------------------------- 18.1/100.3 MB 1.3 MB/s eta 0:01:04
   ------- -------------------------------- 18.6/100.3 MB 1.3 MB/s eta 0:01:04
   ------- -------------------------------- 18.9/100.3 MB 1.3 MB/s eta 0:01:03
   ------- -------------------------------- 19.1/100.3 MB 1.3 MB/s eta 0:01:03
   ------- -------------------------------- 19.4/100.3 MB 1.3 MB/s eta 0:01:03
   ------- -------------------------------- 19.7/100.3 MB 1.3 MB/s eta 0:01:03
   ------- -------------------------------- 19.9/100.3 MB 1.3 MB/s eta 0:01:03
   ------- -------------------------------- 19.9/100.3 MB 1.3 MB/s eta 0:01:03
   ------- -------------------------------- 19.9/100.3 MB 1.3 MB/s eta 0:01:03
   -------- ------------------------------- 20.2/100.3 MB 1.3 MB/s eta 0:01:05
   -------- ------------------------------- 20.4/100.3 MB 1.3 MB/s eta 0:01:04
   -------- ------------------------------- 20.7/100.3 MB 1.3 MB/s eta 0:01:04
   -------- ------------------------------- 21.0/100.3 MB 1.3 MB/s eta 0:01:04
   -------- ------------------------------- 21.2/100.3 MB 1.3 MB/s eta 0:01:04
   -------- ------------------------------- 21.5/100.3 MB 1.3 MB/s eta 0:01:03
   -------- ------------------------------- 21.8/100.3 MB 1.3 MB/s eta 0:01:03
   -------- ------------------------------- 22.0/100.3 MB 1.3 MB/s eta 0:01:03
   -------- ------------------------------- 22.0/100.3 MB 1.3 MB/s eta 0:01:03
   -------- ------------------------------- 22.5/100.3 MB 1.3 MB/s eta 0:01:02
   --------- ------------------------------ 22.8/100.3 MB 1.3 MB/s eta 0:01:02
   --------- ------------------------------ 23.1/100.3 MB 1.3 MB/s eta 0:01:02
   --------- ------------------------------ 23.1/100.3 MB 1.3 MB/s eta 0:01:02
   --------- ------------------------------ 23.3/100.3 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 23.6/100.3 MB 1.2 MB/s eta 0:01:02
   --------- ------------------------------ 23.9/100.3 MB 1.2 MB/s eta 0:01:02
   --------- ------------------------------ 24.1/100.3 MB 1.2 MB/s eta 0:01:02
   --------- ------------------------------ 24.1/100.3 MB 1.2 MB/s eta 0:01:02
   --------- ------------------------------ 24.1/100.3 MB 1.2 MB/s eta 0:01:02
   --------- ------------------------------ 24.1/100.3 MB 1.2 MB/s eta 0:01:02
   --------- ------------------------------ 24.4/100.3 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.6/100.3 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 24.9/100.3 MB 1.2 MB/s eta 0:01:03
   ---------- ----------------------------- 25.2/100.3 MB 1.2 MB/s eta 0:01:02
   ---------- ----------------------------- 25.2/100.3 MB 1.2 MB/s eta 0:01:02
   ---------- ----------------------------- 25.2/100.3 MB 1.2 MB/s eta 0:01:02
   ---------- ----------------------------- 25.4/100.3 MB 1.2 MB/s eta 0:01:04
   ---------- ----------------------------- 25.7/100.3 MB 1.2 MB/s eta 0:01:03
   ---------- ----------------------------- 26.0/100.3 MB 1.2 MB/s eta 0:01:03
   ---------- ----------------------------- 26.2/100.3 MB 1.2 MB/s eta 0:01:03
   ---------- ----------------------------- 26.2/100.3 MB 1.2 MB/s eta 0:01:03
   ---------- ----------------------------- 26.5/100.3 MB 1.2 MB/s eta 0:01:03
   ---------- ----------------------------- 26.7/100.3 MB 1.2 MB/s eta 0:01:03
   ---------- ----------------------------- 27.0/100.3 MB 1.2 MB/s eta 0:01:03
   ---------- ----------------------------- 27.3/100.3 MB 1.2 MB/s eta 0:01:02
   ---------- ----------------------------- 27.5/100.3 MB 1.2 MB/s eta 0:01:02
   ----------- ---------------------------- 27.8/100.3 MB 1.2 MB/s eta 0:01:02
   ----------- ---------------------------- 28.0/100.3 MB 1.2 MB/s eta 0:01:02
   ----------- ---------------------------- 28.3/100.3 MB 1.2 MB/s eta 0:01:01
   ----------- ---------------------------- 28.3/100.3 MB 1.2 MB/s eta 0:01:01
   ----------- ---------------------------- 28.6/100.3 MB 1.2 MB/s eta 0:01:01
   ----------- ---------------------------- 28.8/100.3 MB 1.2 MB/s eta 0:01:01
   ----------- ---------------------------- 29.1/100.3 MB 1.2 MB/s eta 0:01:01
   ----------- ---------------------------- 29.4/100.3 MB 1.2 MB/s eta 0:01:01
   ----------- ---------------------------- 29.6/100.3 MB 1.2 MB/s eta 0:01:00
   ------------ --------------------------- 30.1/100.3 MB 1.2 MB/s eta 0:01:00
   ------------ --------------------------- 30.4/100.3 MB 1.2 MB/s eta 0:00:59
   ------------ --------------------------- 30.7/100.3 MB 1.2 MB/s eta 0:00:59
   ------------ --------------------------- 30.9/100.3 MB 1.2 MB/s eta 0:00:59
   ------------ --------------------------- 31.2/100.3 MB 1.2 MB/s eta 0:00:59
   ------------ --------------------------- 31.5/100.3 MB 1.2 MB/s eta 0:00:58
   ------------ --------------------------- 31.5/100.3 MB 1.2 MB/s eta 0:00:58
   ------------ --------------------------- 32.0/100.3 MB 1.2 MB/s eta 0:00:58
   ------------ --------------------------- 32.2/100.3 MB 1.2 MB/s eta 0:00:58
   ------------ --------------------------- 32.5/100.3 MB 1.2 MB/s eta 0:00:57
   ------------ --------------------------- 32.5/100.3 MB 1.2 MB/s eta 0:00:57
   ------------ --------------------------- 32.5/100.3 MB 1.2 MB/s eta 0:00:57
   ------------ --------------------------- 32.5/100.3 MB 1.2 MB/s eta 0:00:57
   ------------ --------------------------- 32.5/100.3 MB 1.2 MB/s eta 0:00:57
   ------------ --------------------------- 32.5/100.3 MB 1.2 MB/s eta 0:00:57
   ------------- -------------------------- 32.8/100.3 MB 1.2 MB/s eta 0:00:59
   ------------- -------------------------- 33.0/100.3 MB 1.2 MB/s eta 0:00:59
   ------------- -------------------------- 33.3/100.3 MB 1.2 MB/s eta 0:00:58
   ------------- -------------------------- 33.6/100.3 MB 1.2 MB/s eta 0:00:58
   ------------- -------------------------- 33.8/100.3 MB 1.2 MB/s eta 0:00:58
   ------------- -------------------------- 34.1/100.3 MB 1.2 MB/s eta 0:00:58
   ------------- -------------------------- 34.3/100.3 MB 1.2 MB/s eta 0:00:58
   ------------- -------------------------- 34.6/100.3 MB 1.2 MB/s eta 0:00:57
   ------------- -------------------------- 34.9/100.3 MB 1.2 MB/s eta 0:00:57
   -------------- ------------------------- 35.1/100.3 MB 1.2 MB/s eta 0:00:57
   -------------- ------------------------- 35.4/100.3 MB 1.2 MB/s eta 0:00:56
   -------------- ------------------------- 35.7/100.3 MB 1.2 MB/s eta 0:00:56
   -------------- ------------------------- 35.9/100.3 MB 1.2 MB/s eta 0:00:56
   -------------- ------------------------- 36.2/100.3 MB 1.2 MB/s eta 0:00:56
   -------------- ------------------------- 36.4/100.3 MB 1.2 MB/s eta 0:00:56
   -------------- ------------------------- 36.7/100.3 MB 1.2 MB/s eta 0:00:55
   -------------- ------------------------- 36.7/100.3 MB 1.2 MB/s eta 0:00:55
   -------------- ------------------------- 36.7/100.3 MB 1.2 MB/s eta 0:00:55
   -------------- ------------------------- 37.0/100.3 MB 1.1 MB/s eta 0:00:56
   -------------- ------------------------- 37.2/100.3 MB 1.1 MB/s eta 0:00:56
   -------------- ------------------------- 37.5/100.3 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 37.7/100.3 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 37.7/100.3 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 38.0/100.3 MB 1.1 MB/s eta 0:00:56
   --------------- ------------------------ 38.3/100.3 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 38.5/100.3 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 38.8/100.3 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 39.1/100.3 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 39.3/100.3 MB 1.1 MB/s eta 0:00:54
   --------------- ------------------------ 39.6/100.3 MB 1.1 MB/s eta 0:00:54
   --------------- ------------------------ 39.8/100.3 MB 1.1 MB/s eta 0:00:54
   --------------- ------------------------ 40.1/100.3 MB 1.1 MB/s eta 0:00:54
   ---------------- ----------------------- 40.4/100.3 MB 1.1 MB/s eta 0:00:53
   ---------------- ----------------------- 40.6/100.3 MB 1.1 MB/s eta 0:00:53
   ---------------- ----------------------- 40.9/100.3 MB 1.1 MB/s eta 0:00:53
   ---------------- ----------------------- 40.9/100.3 MB 1.1 MB/s eta 0:00:53
   ---------------- ----------------------- 41.2/100.3 MB 1.1 MB/s eta 0:00:53
   ---------------- ----------------------- 41.4/100.3 MB 1.1 MB/s eta 0:00:53
   ---------------- ----------------------- 41.7/100.3 MB 1.1 MB/s eta 0:00:53
   ---------------- ----------------------- 41.9/100.3 MB 1.1 MB/s eta 0:00:52
   ---------------- ----------------------- 41.9/100.3 MB 1.1 MB/s eta 0:00:52
   ---------------- ----------------------- 41.9/100.3 MB 1.1 MB/s eta 0:00:52
   ---------------- ----------------------- 42.2/100.3 MB 1.1 MB/s eta 0:00:53
   ---------------- ----------------------- 42.5/100.3 MB 1.1 MB/s eta 0:00:53
   ----------------- ---------------------- 42.7/100.3 MB 1.1 MB/s eta 0:00:52
   ----------------- ---------------------- 43.0/100.3 MB 1.1 MB/s eta 0:00:52
   ----------------- ---------------------- 43.0/100.3 MB 1.1 MB/s eta 0:00:52
   ----------------- ---------------------- 43.3/100.3 MB 1.1 MB/s eta 0:00:52
   ----------------- ---------------------- 43.5/100.3 MB 1.1 MB/s eta 0:00:52
   ----------------- ---------------------- 43.8/100.3 MB 1.1 MB/s eta 0:00:52
   ----------------- ---------------------- 44.0/100.3 MB 1.1 MB/s eta 0:00:52
   ----------------- ---------------------- 44.3/100.3 MB 1.1 MB/s eta 0:00:52
   ----------------- ---------------------- 44.6/100.3 MB 1.1 MB/s eta 0:00:51
   ----------------- ---------------------- 44.8/100.3 MB 1.1 MB/s eta 0:00:51
   ----------------- ---------------------- 45.1/100.3 MB 1.1 MB/s eta 0:00:51
   ------------------ --------------------- 45.4/100.3 MB 1.1 MB/s eta 0:00:51
   ------------------ --------------------- 45.6/100.3 MB 1.1 MB/s eta 0:00:50
   ------------------ --------------------- 45.9/100.3 MB 1.1 MB/s eta 0:00:50
   ------------------ --------------------- 46.1/100.3 MB 1.1 MB/s eta 0:00:50
   ------------------ --------------------- 46.4/100.3 MB 1.1 MB/s eta 0:00:50
   ------------------ --------------------- 46.7/100.3 MB 1.1 MB/s eta 0:00:50
   ------------------ --------------------- 46.9/100.3 MB 1.1 MB/s eta 0:00:49
   ------------------ --------------------- 47.2/100.3 MB 1.1 MB/s eta 0:00:49
   ------------------ --------------------- 47.4/100.3 MB 1.1 MB/s eta 0:00:49
   ------------------- -------------------- 47.7/100.3 MB 1.1 MB/s eta 0:00:49
   ------------------- -------------------- 48.0/100.3 MB 1.1 MB/s eta 0:00:48
   ------------------- -------------------- 48.2/100.3 MB 1.1 MB/s eta 0:00:48
   ------------------- -------------------- 48.5/100.3 MB 1.1 MB/s eta 0:00:48
   ------------------- -------------------- 48.8/100.3 MB 1.1 MB/s eta 0:00:48
   ------------------- -------------------- 49.0/100.3 MB 1.1 MB/s eta 0:00:47
   ------------------- -------------------- 49.3/100.3 MB 1.1 MB/s eta 0:00:47
   ------------------- -------------------- 49.5/100.3 MB 1.1 MB/s eta 0:00:47
   ------------------- -------------------- 49.8/100.3 MB 1.1 MB/s eta 0:00:47
   ------------------- -------------------- 50.1/100.3 MB 1.1 MB/s eta 0:00:46
   -------------------- ------------------- 50.3/100.3 MB 1.1 MB/s eta 0:00:46
   -------------------- ------------------- 50.6/100.3 MB 1.1 MB/s eta 0:00:46
   -------------------- ------------------- 50.9/100.3 MB 1.1 MB/s eta 0:00:46
   -------------------- ------------------- 51.1/100.3 MB 1.1 MB/s eta 0:00:45
   -------------------- ------------------- 51.4/100.3 MB 1.1 MB/s eta 0:00:45
   -------------------- ------------------- 51.4/100.3 MB 1.1 MB/s eta 0:00:45
   -------------------- ------------------- 51.6/100.3 MB 1.1 MB/s eta 0:00:45

Collecting xgboost
  Downloading xgboost-2.1.4-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in d:\projects\mlproject1\penv\lib\site-packages (from xgboost) (1.24.4)
Requirement already satisfied: scipy in d:\projects\mlproject1\penv\lib\site-packages (from xgboost) (1.10.1)
Downloading xgboost-2.1.4-py3-none-win_amd64.whl (124.9 MB)
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/124.9 MB 1.3 MB/s eta 0:01:37
   ---------------------------------------- 0.8/124.9 MB 1.3 MB/s eta 0:01:37
   ---------------------------------------- 1.0/124.9 MB 1.3 MB/s eta 0:01:36
   ---------------------------------------- 1.3/124.9 MB 1.3 MB/s eta 0:01:36
    --------------------------------------- 1.6/124.9 MB 1.3 MB/s eta 0:01:36
    --------------------------------------- 1.8/124.9 MB 1.3 MB/s eta 0:01:36
    --------------------------------------- 2.1/124.9 MB 1.3 MB/s eta 0:01:36
    --------------------------------------- 2.4/124.9 MB 1.3 MB/s eta 0:01:35
    --------------------------------------- 2.6/124.9 MB 1.3 MB/s eta 0:01:35
    --------------------------------------- 2.9/124.9 MB 1.3 MB/s eta 0:01:35
   - -------------------------------------- 3.1/124.9 MB 1.3 MB/s eta 0:01:35
   - -------------------------------------- 3.4/124.9 MB 1.3 MB/s eta 0:01:35
   - -------------------------------------- 3.7/124.9 MB 1.3 MB/s eta 0:01:34
   - -------------------------------------- 3.9/124.9 MB 1.3 MB/s eta 0:01:34
   - -------------------------------------- 4.2/124.9 MB 1.3 MB/s eta 0:01:34
   - -------------------------------------- 4.5/124.9 MB 1.3 MB/s eta 0:01:34
   - -------------------------------------- 4.7/124.9 MB 1.3 MB/s eta 0:01:33
   - -------------------------------------- 5.0/124.9 MB 1.3 MB/s eta 0:01:33
   - -------------------------------------- 5.2/124.9 MB 1.3 MB/s eta 0:01:33
   - -------------------------------------- 5.5/124.9 MB 1.3 MB/s eta 0:01:35
   - -------------------------------------- 5.8/124.9 MB 1.3 MB/s eta 0:01:33
   - -------------------------------------- 6.0/124.9 MB 1.3 MB/s eta 0:01:34
   -- ------------------------------------- 6.3/124.9 MB 1.3 MB/s eta 0:01:35
   -- ------------------------------------- 6.3/124.9 MB 1.3 MB/s eta 0:01:35
   -- ------------------------------------- 6.6/124.9 MB 1.3 MB/s eta 0:01:35
   -- ------------------------------------- 6.8/124.9 MB 1.2 MB/s eta 0:01:35
   -- ------------------------------------- 7.1/124.9 MB 1.2 MB/s eta 0:01:35
   -- ------------------------------------- 7.3/124.9 MB 1.2 MB/s eta 0:01:35
   -- ------------------------------------- 7.6/124.9 MB 1.2 MB/s eta 0:01:35
   -- ------------------------------------- 7.9/124.9 MB 1.2 MB/s eta 0:01:36
   -- ------------------------------------- 8.1/124.9 MB 1.2 MB/s eta 0:01:35
   -- ------------------------------------- 8.4/124.9 MB 1.2 MB/s eta 0:01:35
   -- ------------------------------------- 8.7/124.9 MB 1.2 MB/s eta 0:01:35
   -- ------------------------------------- 8.9/124.9 MB 1.2 MB/s eta 0:01:35
   -- ------------------------------------- 9.2/124.9 MB 1.2 MB/s eta 0:01:34
   --- ------------------------------------ 9.4/124.9 MB 1.2 MB/s eta 0:01:34
   --- ------------------------------------ 9.7/124.9 MB 1.2 MB/s eta 0:01:34
   --- ------------------------------------ 10.0/124.9 MB 1.2 MB/s eta 0:01:33
   --- ------------------------------------ 10.2/124.9 MB 1.2 MB/s eta 0:01:33
   --- ------------------------------------ 10.5/124.9 MB 1.2 MB/s eta 0:01:33
   --- ------------------------------------ 10.7/124.9 MB 1.2 MB/s eta 0:01:32
   --- ------------------------------------ 11.0/124.9 MB 1.2 MB/s eta 0:01:32
   --- ------------------------------------ 11.3/124.9 MB 1.2 MB/s eta 0:01:32
   --- ------------------------------------ 11.5/124.9 MB 1.2 MB/s eta 0:01:31
   --- ------------------------------------ 11.8/124.9 MB 1.2 MB/s eta 0:01:31
   --- ------------------------------------ 12.1/124.9 MB 1.2 MB/s eta 0:01:32
   --- ------------------------------------ 12.3/124.9 MB 1.2 MB/s eta 0:01:31
   ---- ----------------------------------- 12.6/124.9 MB 1.2 MB/s eta 0:01:31
   ---- ----------------------------------- 12.6/124.9 MB 1.2 MB/s eta 0:01:31
   ---- ----------------------------------- 12.8/124.9 MB 1.2 MB/s eta 0:01:31
   ---- ----------------------------------- 13.1/124.9 MB 1.2 MB/s eta 0:01:31
   ---- ----------------------------------- 13.4/124.9 MB 1.2 MB/s eta 0:01:31
   ---- ----------------------------------- 13.6/124.9 MB 1.2 MB/s eta 0:01:30
   ---- ----------------------------------- 13.9/124.9 MB 1.2 MB/s eta 0:01:30
   ---- ----------------------------------- 14.2/124.9 MB 1.2 MB/s eta 0:01:30
   ---- ----------------------------------- 14.4/124.9 MB 1.2 MB/s eta 0:01:30
   ---- ----------------------------------- 14.7/124.9 MB 1.2 MB/s eta 0:01:29
   ---- ----------------------------------- 14.9/124.9 MB 1.2 MB/s eta 0:01:29
   ---- ----------------------------------- 15.2/124.9 MB 1.2 MB/s eta 0:01:29
   ---- ----------------------------------- 15.5/124.9 MB 1.2 MB/s eta 0:01:29
   ----- ---------------------------------- 15.7/124.9 MB 1.2 MB/s eta 0:01:28
   ----- ---------------------------------- 16.0/124.9 MB 1.2 MB/s eta 0:01:28
   ----- ---------------------------------- 16.3/124.9 MB 1.2 MB/s eta 0:01:28
   ----- ---------------------------------- 16.5/124.9 MB 1.2 MB/s eta 0:01:28
   ----- ---------------------------------- 16.8/124.9 MB 1.2 MB/s eta 0:01:28
   ----- ---------------------------------- 17.0/124.9 MB 1.2 MB/s eta 0:01:27
   ----- ---------------------------------- 17.3/124.9 MB 1.2 MB/s eta 0:01:27
   ----- ---------------------------------- 17.6/124.9 MB 1.2 MB/s eta 0:01:27
   ----- ---------------------------------- 17.8/124.9 MB 1.2 MB/s eta 0:01:27
   ----- ---------------------------------- 18.1/124.9 MB 1.2 MB/s eta 0:01:27
   ----- ---------------------------------- 18.4/124.9 MB 1.2 MB/s eta 0:01:26
   ----- ---------------------------------- 18.6/124.9 MB 1.2 MB/s eta 0:01:26
   ------ --------------------------------- 18.9/124.9 MB 1.2 MB/s eta 0:01:26
   ------ --------------------------------- 19.1/124.9 MB 1.2 MB/s eta 0:01:26
   ------ --------------------------------- 19.4/124.9 MB 1.2 MB/s eta 0:01:26
   ------ --------------------------------- 19.7/124.9 MB 1.2 MB/s eta 0:01:25
   ------ --------------------------------- 19.9/124.9 MB 1.2 MB/s eta 0:01:25
   ------ --------------------------------- 20.2/124.9 MB 1.2 MB/s eta 0:01:25
   ------ --------------------------------- 20.4/124.9 MB 1.2 MB/s eta 0:01:25
   ------ --------------------------------- 20.7/124.9 MB 1.2 MB/s eta 0:01:24
   ------ --------------------------------- 21.0/124.9 MB 1.2 MB/s eta 0:01:24
   ------ --------------------------------- 21.2/124.9 MB 1.2 MB/s eta 0:01:24
   ------ --------------------------------- 21.5/124.9 MB 1.2 MB/s eta 0:01:24
   ------ --------------------------------- 21.8/124.9 MB 1.2 MB/s eta 0:01:23
   ------- -------------------------------- 22.0/124.9 MB 1.2 MB/s eta 0:01:23
   ------- -------------------------------- 22.3/124.9 MB 1.2 MB/s eta 0:01:23
   ------- -------------------------------- 22.5/124.9 MB 1.2 MB/s eta 0:01:22
   ------- -------------------------------- 22.8/124.9 MB 1.2 MB/s eta 0:01:22
   ------- -------------------------------- 23.1/124.9 MB 1.2 MB/s eta 0:01:22
   ------- -------------------------------- 23.3/124.9 MB 1.3 MB/s eta 0:01:22
   ------- -------------------------------- 23.6/124.9 MB 1.3 MB/s eta 0:01:22
   ------- -------------------------------- 23.9/124.9 MB 1.2 MB/s eta 0:01:22
   ------- -------------------------------- 24.1/124.9 MB 1.3 MB/s eta 0:01:21
   ------- -------------------------------- 24.4/124.9 MB 1.3 MB/s eta 0:01:21
   ------- -------------------------------- 24.6/124.9 MB 1.3 MB/s eta 0:01:21
   ------- -------------------------------- 24.9/124.9 MB 1.3 MB/s eta 0:01:20
   -------- ------------------------------- 25.2/124.9 MB 1.3 MB/s eta 0:01:20
   -------- ------------------------------- 25.4/124.9 MB 1.3 MB/s eta 0:01:20
   -------- ------------------------------- 25.7/124.9 MB 1.3 MB/s eta 0:01:20
   -------- ------------------------------- 26.0/124.9 MB 1.3 MB/s eta 0:01:19
   -------- ------------------------------- 26.2/124.9 MB 1.3 MB/s eta 0:01:19
   -------- ------------------------------- 26.5/124.9 MB 1.3 MB/s eta 0:01:19
   -------- ------------------------------- 26.7/124.9 MB 1.3 MB/s eta 0:01:19
   -------- ------------------------------- 27.0/124.9 MB 1.3 MB/s eta 0:01:19
   -------- ------------------------------- 27.3/124.9 MB 1.3 MB/s eta 0:01:18
   -------- ------------------------------- 27.5/124.9 MB 1.3 MB/s eta 0:01:18
   -------- ------------------------------- 27.8/124.9 MB 1.3 MB/s eta 0:01:18
   -------- ------------------------------- 28.0/124.9 MB 1.3 MB/s eta 0:01:18
   --------- ------------------------------ 28.3/124.9 MB 1.3 MB/s eta 0:01:18
   --------- ------------------------------ 28.6/124.9 MB 1.3 MB/s eta 0:01:17
   --------- ------------------------------ 28.8/124.9 MB 1.3 MB/s eta 0:01:17
   --------- ------------------------------ 29.1/124.9 MB 1.3 MB/s eta 0:01:17
   --------- ------------------------------ 29.4/124.9 MB 1.3 MB/s eta 0:01:17
   --------- ------------------------------ 29.6/124.9 MB 1.3 MB/s eta 0:01:16
   --------- ------------------------------ 29.9/124.9 MB 1.3 MB/s eta 0:01:16
   --------- ------------------------------ 30.1/124.9 MB 1.3 MB/s eta 0:01:16
   --------- ------------------------------ 30.4/124.9 MB 1.3 MB/s eta 0:01:16
   --------- ------------------------------ 30.7/124.9 MB 1.3 MB/s eta 0:01:15
   --------- ------------------------------ 30.9/124.9 MB 1.3 MB/s eta 0:01:15
   --------- ------------------------------ 31.2/124.9 MB 1.3 MB/s eta 0:01:15
   ---------- ----------------------------- 31.5/124.9 MB 1.3 MB/s eta 0:01:15
   ---------- ----------------------------- 31.7/124.9 MB 1.3 MB/s eta 0:01:15
   ---------- ----------------------------- 32.0/124.9 MB 1.3 MB/s eta 0:01:15
   ---------- ----------------------------- 32.2/124.9 MB 1.3 MB/s eta 0:01:14
   ---------- ----------------------------- 32.5/124.9 MB 1.3 MB/s eta 0:01:14
   ---------- ----------------------------- 32.8/124.9 MB 1.3 MB/s eta 0:01:14
   ---------- ----------------------------- 33.0/124.9 MB 1.3 MB/s eta 0:01:14
   ---------- ----------------------------- 33.3/124.9 MB 1.3 MB/s eta 0:01:13
   ---------- ----------------------------- 33.6/124.9 MB 1.3 MB/s eta 0:01:13
   ---------- ----------------------------- 33.6/124.9 MB 1.3 MB/s eta 0:01:13
   ---------- ----------------------------- 33.8/124.9 MB 1.3 MB/s eta 0:01:13
   ---------- ----------------------------- 34.1/124.9 MB 1.2 MB/s eta 0:01:13
   ---------- ----------------------------- 34.3/124.9 MB 1.2 MB/s eta 0:01:13
   ----------- ---------------------------- 34.6/124.9 MB 1.2 MB/s eta 0:01:13
   ----------- ---------------------------- 34.9/124.9 MB 1.2 MB/s eta 0:01:13
   ----------- ---------------------------- 35.1/124.9 MB 1.2 MB/s eta 0:01:12
   ----------- ---------------------------- 35.4/124.9 MB 1.2 MB/s eta 0:01:12
   ----------- ---------------------------- 35.7/124.9 MB 1.2 MB/s eta 0:01:12
   ----------- ---------------------------- 35.9/124.9 MB 1.2 MB/s eta 0:01:12
   ----------- ---------------------------- 36.2/124.9 MB 1.2 MB/s eta 0:01:12
   ----------- ---------------------------- 36.4/124.9 MB 1.2 MB/s eta 0:01:11
   ----------- ---------------------------- 36.7/124.9 MB 1.2 MB/s eta 0:01:11
   ----------- ---------------------------- 37.0/124.9 MB 1.2 MB/s eta 0:01:11
   ----------- ---------------------------- 37.2/124.9 MB 1.2 MB/s eta 0:01:11
   ------------ --------------------------- 37.5/124.9 MB 1.2 MB/s eta 0:01:10
   ------------ --------------------------- 37.7/124.9 MB 1.2 MB/s eta 0:01:10
   ------------ --------------------------- 38.0/124.9 MB 1.2 MB/s eta 0:01:10
   ------------ --------------------------- 38.3/124.9 MB 1.2 MB/s eta 0:01:10
   ------------ --------------------------- 38.5/124.9 MB 1.2 MB/s eta 0:01:10
   ------------ --------------------------- 38.8/124.9 MB 1.2 MB/s eta 0:01:09
   ------------ --------------------------- 39.1/124.9 MB 1.2 MB/s eta 0:01:09
   ------------ --------------------------- 39.3/124.9 MB 1.2 MB/s eta 0:01:09
   ------------ --------------------------- 39.6/124.9 MB 1.2 MB/s eta 0:01:09
   ------------ --------------------------- 39.8/124.9 MB 1.2 MB/s eta 0:01:09
   ------------ --------------------------- 39.8/124.9 MB 1.2 MB/s eta 0:01:09
   ------------ --------------------------- 40.1/124.9 MB 1.2 MB/s eta 0:01:09
   ------------ --------------------------- 40.4/124.9 MB 1.2 MB/s eta 0:01:08
   ------------- -------------------------- 40.6/124.9 MB 1.2 MB/s eta 0:01:08
   ------------- -------------------------- 40.9/124.9 MB 1.2 MB/s eta 0:01:08
   ------------- -------------------------- 41.2/124.9 MB 1.2 MB/s eta 0:01:08
   ------------- -------------------------- 41.4/124.9 MB 1.2 MB/s eta 0:01:08
   ------------- -------------------------- 41.7/124.9 MB 1.2 MB/s eta 0:01:08
   ------------- -------------------------- 41.9/124.9 MB 1.2 MB/s eta 0:01:07
   ------------- -------------------------- 42.2/124.9 MB 1.2 MB/s eta 0:01:07
   ------------- -------------------------- 42.5/124.9 MB 1.2 MB/s eta 0:01:07
   ------------- -------------------------- 42.7/124.9 MB 1.2 MB/s eta 0:01:06
   ------------- -------------------------- 43.0/124.9 MB 1.2 MB/s eta 0:01:06
   ------------- -------------------------- 43.3/124.9 MB 1.2 MB/s eta 0:01:06
   ------------- -------------------------- 43.5/124.9 MB 1.2 MB/s eta 0:01:06
   -------------- ------------------------- 43.8/124.9 MB 1.2 MB/s eta 0:01:06
   -------------- ------------------------- 44.0/124.9 MB 1.2 MB/s eta 0:01:05
   -------------- ------------------------- 44.3/124.9 MB 1.3 MB/s eta 0:01:05
   -------------- ------------------------- 44.6/124.9 MB 1.3 MB/s eta 0:01:05
   -------------- ------------------------- 44.8/124.9 MB 1.3 MB/s eta 0:01:04
   -------------- ------------------------- 45.1/124.9 MB 1.3 MB/s eta 0:01:04
   -------------- ------------------------- 45.4/124.9 MB 1.3 MB/s eta 0:01:04
   -------------- ------------------------- 45.6/124.9 MB 1.3 MB/s eta 0:01:04
   -------------- ------------------------- 45.9/124.9 MB 1.3 MB/s eta 0:01:04
   -------------- ------------------------- 46.1/124.9 MB 1.3 MB/s eta 0:01:03
   -------------- ------------------------- 46.4/124.9 MB 1.3 MB/s eta 0:01:03
   -------------- ------------------------- 46.7/124.9 MB 1.3 MB/s eta 0:01:03
   --------------- ------------------------ 46.9/124.9 MB 1.3 MB/s eta 0:01:03
   --------------- ------------------------ 47.2/124.9 MB 1.3 MB/s eta 0:01:03
   --------------- ------------------------ 47.4/124.9 MB 1.3 MB/s eta 0:01:02
   --------------- ------------------------ 47.7/124.9 MB 1.3 MB/s eta 0:01:02
   --------------- ------------------------ 48.0/124.9 MB 1.3 MB/s eta 0:01:02
   --------------- ------------------------ 48.2/124.9 MB 1.3 MB/s eta 0:01:02
   --------------- ------------------------ 48.5/124.9 MB 1.3 MB/s eta 0:01:02
   --------------- ------------------------ 48.8/124.9 MB 1.3 MB/s eta 0:01:01
   --------------- ------------------------ 49.0/124.9 MB 1.3 MB/s eta 0:01:01
   --------------- ------------------------ 49.3/124.9 MB 1.3 MB/s eta 0:01:01
   --------------- ------------------------ 49.5/124.9 MB 1.3 MB/s eta 0:01:01
   --------------- ------------------------ 49.8/124.9 MB 1.3 MB/s eta 0:01:00
   ---------------- ----------------------- 50.1/124.9 MB 1.3 MB/s eta 0:01:00
   ---------------- ----------------------- 50.3/124.9 MB 1.3 MB/s eta 0:01:00
   ---------------- ----------------------- 50.6/124.9 MB 1.3 MB/s eta 0:01:00
   ---------------- ----------------------- 50.9/124.9 MB 1.3 MB/s eta 0:00:59
   ---------------- ----------------------- 51.1/124.9 MB 1.3 MB/s eta 0:00:59
   ---------------- ----------------------- 51.4/124.9 MB 1.3 MB/s eta 0:00:59
   ---------------- ----------------------- 51.6/124.9 MB 1.3 MB/s eta 0:00:59
   ---------------- ----------------------- 51.9/124.9 MB 1.3 MB/s eta 0:00:59
   ---------------- ----------------------- 52.2/124.9 MB 1.3 MB/s eta 0:00:58
   ---------------- ----------------------- 52.4/124.9 MB 1.3 MB/s eta 0:00:58
   ---------------- ----------------------- 52.7/124.9 MB 1.3 MB/s eta 0:00:58
   ---------------- ----------------------- 53.0/124.9 MB 1.3 MB/s eta 0:00:58
   ----------------- ---------------------- 53.2/124.9 MB 1.3 MB/s eta 0:00:58
   ----------------- ---------------------- 53.5/124.9 MB 1.3 MB/s eta 0:00:57
   ----------------- ---------------------- 53.7/124.9 MB 1.3 MB/s eta 0:00:57
   ----------------- ---------------------- 54.0/124.9 MB 1.3 MB/s eta 0:00:57
   ----------------- ---------------------- 54.3/124.9 MB 1.3 MB/s eta 0:00:57
   ----------------- ---------------------- 54.5/124.9 MB 1.3 MB/s eta 0:00:56
   ----------------- ---------------------- 54.8/124.9 MB 1.3 MB/s eta 0:00:56
   ----------------- ---------------------- 55.1/124.9 MB 1.3 MB/s eta 0:00:56
   ----------------- ---------------------- 55.3/124.9 MB 1.3 MB/s eta 0:00:56
   ----------------- ---------------------- 55.6/124.9 MB 1.3 MB/s eta 0:00:56
   ----------------- ---------------------- 55.8/124.9 MB 1.3 MB/s eta 0:00:55
   ----------------- ---------------------- 56.1/124.9 MB 1.3 MB/s eta 0:00:55
   ------------------ --------------------- 56.4/124.9 MB 1.3 MB/s eta 0:00:55
   ------------------ --------------------- 56.6/124.9 MB 1.3 MB/s eta 0:00:55
   ------------------ --------------------- 56.9/124.9 MB 1.3 MB/s eta 0:00:54
   ------------------ --------------------- 57.1/124.9 MB 1.3 MB/s eta 0:00:54
   ------------------ --------------------- 57.4/124.9 MB 1.3 MB/s eta 0:00:54
   ------------------ --------------------- 57.7/124.9 MB 1.3 MB/s eta 0:00:54
   ------------------ --------------------- 57.9/124.9 MB 1.3 MB/s eta 0:00:54
   ------------------ --------------------- 58.2/124.9 MB 1.3 MB/s eta 0:00:53
   ------------------ --------------------- 58.5/124.9 MB 1.3 MB/s eta 0:00:53
   ------------------ --------------------- 58.7/124.9 MB 1.3 MB/s eta 0:00:53
   ------------------ --------------------- 58.7/124.9 MB 1.3 MB/s eta 0:00:53
   ------------------ --------------------- 59.2/124.9 MB 1.3 MB/s eta 0:00:53
   ------------------ --------------------- 59.2/124.9 MB 1.3 MB/s eta 0:00:53
   ------------------- -------------------- 59.8/124.9 MB 1.3 MB/s eta 0:00:52
   ------------------- -------------------- 60.0/124.9 MB 1.3 MB/s eta 0:00:52
   ------------------- -------------------- 60.3/124.9 MB 1.3 MB/s eta 0:00:52
   ------------------- -------------------- 60.6/124.9 MB 1.3 MB/s eta 0:00:52
   ------------------- -------------------- 60.8/124.9 MB 1.3 MB/s eta 0:00:51
   ------------------- -------------------- 61.1/124.9 MB 1.3 MB/s eta 0:00:51
   ------------------- -------------------- 61.3/124.9 MB 1.3 MB/s eta 0:00:51
   ------------------- -------------------- 61.6/124.9 MB 1.3 MB/s eta 0:00:51
   ------------------- -------------------- 61.9/124.9 MB 1.3 MB/s eta 0:00:51
   ------------------- -------------------- 62.1/124.9 MB 1.3 MB/s eta 0:00:50
   ------------------- -------------------- 62.4/124.9 MB 1.3 MB/s eta 0:00:50
   -------------------- ------------------- 62.7/124.9 MB 1.3 MB/s eta 0:00:50
   -------------------- ------------------- 62.9/124.9 MB 1.3 MB/s eta 0:00:50
   -------------------- ------------------- 63.2/124.9 MB 1.3 MB/s eta 0:00:50
   -------------------- ------------------- 63.4/124.9 MB 1.3 MB/s eta 0:00:49
   -------------------- ------------------- 63.7/124.9 MB 1.3 MB/s eta 0:00:49
   -------------------- ------------------- 64.0/124.9 MB 1.3 MB/s eta 0:00:49

In [7]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
#models
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
import warnings

In [9]:
df = pd.read_csv(r'D:\projects\mlproject1\Notebook\data\StudentsPerformance.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [10]:
X = df.drop(columns=['math score'], axis=1)
y = df['math score']

In [15]:
num_features =[feat for feat in X.columns if X[feat].dtype !='O']
cat_features = [feat for feat in X.columns if X[feat].dtype == 'O']

In [16]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
num_transformer = StandardScaler()
cat_transformer = OneHotEncoder()

preprocessor = ColumnTransformer([
    ('num', num_transformer, num_features),
    ('cat', cat_transformer, cat_features)
])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 7), (200, 7), (800,), (200,))

In [21]:
x_train_transformed = preprocessor.fit_transform(X_train)
x_test_transformed = preprocessor.transform(X_test)
x_train_transformed.shape, x_test_transformed.shape

((800, 19), (200, 19))

In [23]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_square = r2_score(true, predicted)
    return mae, mse, rmse, r2_square

In [24]:
models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(),
    'Lasso Regression': Lasso(),
    'KNN Regressor': KNeighborsRegressor(),
    'Random Forest Regressor': RandomForestRegressor(),
    'Gradient Boosting Regressor': GradientBoostingRegressor(),
    'AdaBoost Regressor': AdaBoostRegressor(),
    'XGBoost Regressor': XGBRegressor(),
    'CatBoost Regressor': CatBoostRegressor(verbose=0),
    'Decision Tree Regressor': DecisionTreeRegressor()}

model_list = []
r2_list = []

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(x_train_transformed, y_train)

    y_train_pred = model.predict(x_train_transformed)
    y_test_pred = model.predict(x_test_transformed)

    train_mae, train_mse, train_rmse, train_r2 = evaluate_model(y_train, y_train_pred)
    test_mae, test_mse, test_rmse, test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    r2_list.append(test_r2)





    print("train mae: {:,.2f}".format(train_mae))
    print(f'Train MSE: {train_mse}')
    print(f'Train RMSE: {train_rmse}')
    print(f'Train R2 Score: {train_r2}')  

    print("---------------------------------------")
    print(f'Test MAE: {test_mae}')
    print(f'Test MSE: {test_mse}')
    print(f'Test RMSE: {test_rmse}')
    print(f'Test R2 Score: {test_r2}')
    
    print('='*50)
    print('\n')

Linear Regression
train mae: 4.27
Train MSE: 28.33487038064859
Train RMSE: 5.323050852720514
Train R2 Score: 0.8743172040139593
---------------------------------------
Test MAE: 4.21476314247485
Test MSE: 29.095169866715477
Test RMSE: 5.393993869732841
Test R2 Score: 0.8804332983749565
==================================================


Ridge Regression
train mae: 4.27
Train MSE: 28.337741791088877
Train RMSE: 5.323320560617112
Train R2 Score: 0.8743044675204547
---------------------------------------
Test MAE: 4.211112826071164
Test MSE: 29.056601626694828
Test RMSE: 5.390417574427312
Test R2 Score: 0.8805917946912825
==================================================


Lasso Regression
train mae: 5.21
Train MSE: 43.46106018771194
Train RMSE: 6.592500298650879
Train R2 Score: 0.8072231322208645
---------------------------------------
Test MAE: 5.155701094273798
Test MSE: 42.47556715227398
Test RMSE: 6.517328221922997
Test R2 Score: 0.8254465092551198
==================================================


KNN Regressor
train mae: 4.51
Train MSE: 32.48015
Train RMSE: 5.699135899414928
Train R2 Score: 0.855930307384291
---------------------------------------
Test MAE: 5.599
Test MSE: 52.5714
Test RMSE: 7.2506137671234425
Test R2 Score: 0.7839576491010051
==================================================


Random Forest Regressor
train mae: 1.83
Train MSE: 5.254007263020833
Train RMSE: 2.2921621371580225
Train R2 Score: 0.9766952057984919
---------------------------------------
Test MAE: 4.6184125
Test MSE: 36.02471771180555
Test RMSE: 6.002059455870589
Test R2 Score: 0.8519562974367977
==================================================


Gradient Boosting Regressor
train mae: 3.72
Train MSE: 21.40856892429239
Train RMSE: 4.626939477050936
Train R2 Score: 0.9050396644022572
---------------------------------------
Test MAE: 4.306285751357842
Test MSE: 31.09631619644443
Test RMSE: 5.576407104618926
Test R2 Score: 0.8722095805822492
==================================================


AdaBoost Regressor
train mae: 4.79
Train MSE: 34.3903310400782
Train RMSE: 5.864326989525584
Train R2 Score: 0.8474574648855826
---------------------------------------
Test MAE: 4.765285517655858
Test MSE: 36.599129739712474
Test RMSE: 6.04972145967998
Test R2 Score: 0.8495957492129789
==================================================


XGBoost Regressor
train mae: 0.69
Train MSE: 1.0146163961652577
Train RMSE: 1.0072816866027385
Train R2 Score: 0.9954995444196413
---------------------------------------
Test MAE: 5.103629446029663
Test MSE: 43.50391987982302
Test RMSE: 6.595750137764697
Test R2 Score: 0.8212204901494256
==================================================


CatBoost Regressor
train mae: 2.41
Train MSE: 9.257805405523678
Train RMSE: 3.042664195326799
Train R2 Score: 0.9589358676277713
---------------------------------------
Test MAE: 4.608757793199379
Test MSE: 36.055319852755574
Test RMSE: 6.004608218090134
Test R2 Score: 0.8518305378322716
==================================================


Decision Tree Regressor
train mae: 0.02
Train MSE: 0.078125
Train RMSE: 0.2795084971874737
Train R2 Score: 0.9996534669718089
---------------------------------------
Test MAE: 6.13
Test MSE: 59.62
Test RMSE: 7.721398836998384
Test R2 Score: 0.7549914029187338
==================================================

In [25]:
pd.DataFrame({'Model': model_list, 'R2 Score': r2_list}).sort_values(by='R2 Score', ascending=False)

                         Model  R2 Score
1             Ridge Regression  0.880592
0            Linear Regression  0.880433
5  Gradient Boosting Regressor  0.872210
4      Random Forest Regressor  0.851956
8           CatBoost Regressor  0.851831
6           AdaBoost Regressor  0.849596
2             Lasso Regression  0.825447
7            XGBoost Regressor  0.821220
3                KNN Regressor  0.783958
9      Decision Tree Regressor  0.754991